import canonicalLaneMathlib.AdmissibleClass

namespace HautevilleHouse
namespace DevelopmentalBiologyGastrulationCanonicalLaneLean

end DevelopmentalBiologyGastrulationCanonicalLaneLean
end HautevilleHouse